name: Deploy Azure Broker

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: azure-broker
  cancel-in-progress: true

env:
  AZURE_FUNCTIONAPP_NAME: splash-demo-broker-nh-y1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy broker
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: .
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          respect-funcignore: true
          remote-build: true
          scm-do-build-during-deployment: true
          enable-oryx-build: true
